
# name of the generated executable
BIN := popcorn-pthread

# list of the source files
SRC := popcorn-pthread.c

# list additional libraries
LIBS := /lib/libpthread.a

include /usr/local/popcorn/share/build/Makefile
