
# name of the generated executable
BIN := popcorn-prime_sum

# list of the source files
SRC := popcorn-prime_sum.c

# list additional libraries
LIBS := /lib/libpthread.a

include /usr/local/popcorn/share/build/Makefile
