
# name of the generated executable
BIN := popcorn-migratemep

# list of the source files
SRC := popcorn-migratemep.c

# list additional libraries
LIBS := /lib/libpthread.a

include /usr/local/popcorn/share/build/Makefile
